config/routes.rb
Rails.application.routes.draw do
  #List
  get 'tasks', to: 'tasks#index'
  #Create
  get 'tasks/new', to: 'tasks#new', as: 'new_task'
  post 'tasks', to: 'tasks#create', as: 'create'
  #Update
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch 'tasks/:id', to: 'tasks#update', as: 'task'
  #Show
  get 'tasks/:id', to: 'tasks#show', as: 'show'
  #Delete
  delete 'tasks/:id', to: 'tasks#destroy', as: 'destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save

    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to task_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

    private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/releases/v5.10.1/js/all.js" data-auto-replace-svg="nest"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.text_field :title, placeholder: 'Title of the task' %>
  <%= f.text_field :details, placeholder: 'Details to do' %>
  <% if @task.id %>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit the Task</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks List</h1>

<% @tasks.each do |task| %>
  <p><input type="checkbox" <%= 'checked' if task.completed %> >
  <%= link_to task.title, "/tasks/#{task['id']}" %>
  <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, destroy_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %></p>
<% end %>

  <p><%= link_to "Add a new task", new_task_path %></p>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<p><%= link_to "Back to list", tasks_path %></p>

app/views/tasks/show.html.erb
<h1>Task Details</h1>

<h2><%= @task['title'] %></h2>
<p><%= @task['details'] %></p>
<div>
    <p>  <input type="checkbox" name="details">
    <%= 'checked' if @task.completed %>
   This task is <%= "not" if !@task.completed %> completed </p>
</div>

<p><%= link_to "Back to list", tasks_path %></p>

<div class= 'edit_task'>
  <p><%= link_to "Edit that task", edit_path %></p>
</div>